global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'coin-api'
    static_configs:
      - targets: ['coin-api:3001']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']